### ISSUE TITLE
메인 페이지 -> 검색 페이지 연결

### ISSUE THREAD

**Issue by yanJuicy** [Challenge02/HangehaeMusicClub-FE#27]
# Description
메인 페이지 검색창에 검색어 입력 후 검색 페이지로 연결 작업

## Todo
- [ ] 검색창에 검색어를 가져와서 검색 페이지로 넘겨줌
- [ ] 검색어를 검색 페이지에서 보여줌
- [ ] 검색 페이지에서 검색 결과를 보여줌
