### ISSUE TITLE
검색 페이지 JS 작성

### ISSUE THREAD

**Issue by 1Tsw0rd** [Challenge02/HangehaeMusicClub-FE#6]
# Description
검색 결과 출력 페이지

## Todo
- [ ] 검색 입력란 ajax 기틀
- [ ] 아티스트 검색결과  ajax 기틀
- [ ] 곡 검색결과  ajax 기틀
- [ ] 가사 검색결과 ajax 기틀
- [ ] 더보기 ajax 기틀

## Etc
기타사항을 작성해주세요.
